import { Bar, BarChart, CartesianGrid, Cell, PolarAngleAxis, PolarGrid, PolarRadiusAxis, Radar, RadarChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import { BRAND_COLOR, COLORS, RADAR_COLOR, RADAR_DATA, RADAR_MODELOS } from "../../data";
import { ChartTooltip } from "../Shared";
import "./style.css";

export default function Comparison({ segment, segmentBars, scatterData }) {
  return <section className="insights-comparison insights-chart-grid">
    <div className="insights-chart-half"><div className="insights-panel"><header className="insights-panel-header"><h2>Feature-parity por marca: {segment}</h2><p>% de versões com pelo menos um recurso ADAS de série</p></header><ResponsiveContainer width="100%" height={210}><BarChart data={segmentBars} margin={{ top: 6, right: 10, left: -18, bottom: 0 }}><CartesianGrid stroke="#e8edf2" vertical={false} /><XAxis dataKey="marca" tick={{ fill: COLORS.muted, fontSize: 11 }} axisLine={{ stroke: COLORS.border }} tickLine={false} /><YAxis tick={{ fill: COLORS.muted, fontSize: 11 }} axisLine={false} tickLine={false} unit="%" width={40} /><Tooltip content={<ChartTooltip suffix="%" />} /><Bar dataKey="pct" name="Adoção" radius={[3, 3, 0, 0]}>{segmentBars.map((item) => <Cell key={item.marca} fill={BRAND_COLOR[item.marca] || COLORS.muted} />)}</Bar></BarChart></ResponsiveContainer></div></div>
    <div className="insights-chart-half"><div className="insights-panel"><header className="insights-panel-header"><h2>Comparativo multi-especificação</h2><p>Índices normalizados de modelos do segmento SUV compacto</p></header><ResponsiveContainer width="100%" height={210}><RadarChart data={RADAR_DATA} outerRadius="72%"><PolarGrid stroke="#e8edf2" /><PolarAngleAxis dataKey="atributo" tick={{ fill: COLORS.textMuted, fontSize: 10.5 }} /><PolarRadiusAxis tick={false} axisLine={false} domain={[0, 100]} />{RADAR_MODELOS.map((model) => <Radar key={model} name={model} dataKey={model} stroke={RADAR_COLOR[model]} fill={RADAR_COLOR[model]} fillOpacity={0.08} strokeWidth={1.75} />)}<Tooltip content={<ChartTooltip />} /></RadarChart></ResponsiveContainer><div className="insights-radar-legend">{RADAR_MODELOS.map((model) => <span key={model}><i style={{ background: RADAR_COLOR[model] }} />{model}</span>)}</div></div></div>
    <div className="insights-chart-wide"><div className="insights-panel"><header className="insights-panel-header"><h2>Potência x consumo</h2><p>Cada ponto é um modelo ou versão: {segment}</p></header><ResponsiveContainer width="100%" height={220}><ScatterChart margin={{ top: 6, right: 20, left: -14, bottom: 4 }}><CartesianGrid stroke="#e8edf2" /><XAxis type="number" dataKey="potencia" name="Potência" unit=" cv" tick={{ fill: COLORS.muted, fontSize: 11 }} axisLine={{ stroke: COLORS.border }} tickLine={false} /><YAxis type="number" dataKey="consumo" name="Consumo" unit=" km/l" tick={{ fill: COLORS.muted, fontSize: 11 }} axisLine={{ stroke: COLORS.border }} tickLine={false} width={44} /><ZAxis range={[70, 70]} /><Tooltip content={({ active, payload }) => { if (!active || !payload?.length) return null; const item = payload[0].payload; return <ChartTooltip active payload={[{ name: "Potência", value: `${item.potencia} cv`, color: BRAND_COLOR[item.marca] }]} label={`${item.marca} ${item.modelo}`} />; }} />{Object.keys(BRAND_COLOR).map((brand) => <Scatter key={brand} name={brand} data={scatterData.filter((item) => item.marca === brand)} fill={BRAND_COLOR[brand]} />)}</ScatterChart></ResponsiveContainer></div></div>
  </section>;
}
