export const sources = {
    manufacturer: {
        id: 'manufacturer',
        name: 'Ford',
        description: 'Informações técnicas disponibilizadas pelo fabricante.',
        type: 'Fabricante',
    },
    technicalDatabase: {
        id: 'technicalDatabase',
        name: 'Base técnica',
        description: 'Dados técnicos consolidados para consulta.',
        type: 'Base de dados',
    },
    internalAnalysis: {
        id: 'internalAnalysis',
        name: 'Análise Lumen',
        description: 'Informações geradas a partir da análise dos dados disponíveis.',
        type: 'Análise',
    },
};

const mustang = {
    id: '1',
    brand: 'Ford',
    name: 'Mustang GT 2024',
    image: 'https://raw.githubusercontent.com/LUMEN-7/images/refs/heads/main/mustang.png',
    description: 'O Mustang GT combina potência, design esportivo e tecnologia para entregar uma experiência de direção marcante.',
    lastUpdated: '03 set 2026',
    updatedAgo: 'há 3 dias',
    specs: {
        engine: { value: '5.0 V8', source: 'manufacturer' },
        power: { value: '488 cv', source: 'manufacturer' },
        type: { value: 'Coupé', source: 'manufacturer' },
        consumption: { value: '8 km/l', source: 'technicalDatabase' },
        model: { value: 'Mustang GT', source: 'manufacturer' },
        brand: { value: 'Ford', source: 'manufacturer' },
        year: { value: '2024', source: 'manufacturer' },
        driveModes: { value: 'Sport, Eco, Comfort', source: 'manufacturer' },
        torque: { value: '57,3 kgfm', source: 'manufacturer' },
        powerRpm: { value: '7.250 rpm', source: 'manufacturer' },
        torqueRpm: { value: '4.900 rpm', source: 'manufacturer' },
        transmission: { value: 'Automática', source: 'manufacturer' },
        drivetrain: { value: 'Traseira', source: 'manufacturer' },
        cityConsumption: { value: '6,2 km/l', source: 'technicalDatabase' },
        highwayConsumption: { value: '9,8 km/l', source: 'technicalDatabase' },
        length: { value: '4.810 mm', source: 'manufacturer' },
        width: { value: '1.916 mm', source: 'manufacturer' },
        height: { value: '1.397 mm', source: 'manufacturer' },
        wheelbase: { value: '2.719 mm', source: 'manufacturer' },
        tireType: { value: 'Performance', source: 'manufacturer' },
        rim: { value: '19"', source: 'manufacturer' },
        tireWidth: { value: '255 mm', source: 'manufacturer' },
        tireProfile: { value: '40', source: 'manufacturer' },
        tankCapacity: { value: '61 L', source: 'manufacturer' },
        fuelType: { value: 'Gasolina', source: 'manufacturer' },
        loadCapacity: { value: '380 kg', source: 'technicalDatabase' },
        towingCapacity: { value: 'Não informado', source: 'technicalDatabase' },
    },
    sections: {
        performance: [
            { value: '0 a 100 km/h em cerca de 4,2 segundos', source: 'technicalDatabase' },
            { value: 'Tração traseira', source: 'manufacturer' },
            { value: 'Câmbio automático de alta performance', source: 'manufacturer' },
        ],
        security: [
            { value: 'Controle de estabilidade', source: 'manufacturer' },
            { value: 'Assistente de frenagem', source: 'manufacturer' },
            { value: 'Airbags múltiplos', source: 'manufacturer' },
        ],
        technology: [
            { value: 'Painel digital', source: 'manufacturer' },
            { value: 'Central multimídia', source: 'manufacturer' },
            { value: 'Apple CarPlay e Android Auto', source: 'manufacturer' },
        ],
        comfort: [
            { value: 'Bancos esportivos', source: 'manufacturer' },
            { value: 'Ar-condicionado digital', source: 'manufacturer' },
            { value: 'Acabamento premium', source: 'internalAnalysis' },
        ],
    },
    aiAnalysis: {
        strengths: ['Motor V8 potente e resposta imediata', 'Experiência de condução esportiva', 'Design icônico e alta presença visual'],
        weaknesses: ['Consumo elevado em uso urbano', 'Menor praticidade para uso familiar', 'Porta-malas limitado para viagens longas'],
        bestUse: 'Estrada, condução esportiva e uso recreativo',
        competitors: ['Chevrolet Camaro', 'Dodge Challenger', 'BMW Série 4 Coupé'],
    },
};

const bronco = {
    id: '2',
    brand: 'Ford',
    name: 'Bronco 2021',
    image: 'https://raw.githubusercontent.com/LUMEN-7/images/refs/heads/main/carros/2021_ford_bronco.png',
    description: 'O Bronco é um SUV robusto, feito para aventura, com presença forte e capacidade off-road.',
    lastUpdated: '03 set 2026',
    updatedAgo: 'há 3 dias',
    specs: {
        engine: { value: '2.7 V6', source: 'manufacturer' },
        power: { value: '330 cv', source: 'manufacturer' },
        type: { value: 'SUV', source: 'manufacturer' },
        consumption: { value: '7 km/l', source: 'technicalDatabase' },
        model: { value: 'Bronco', source: 'manufacturer' },
        brand: { value: 'Ford', source: 'manufacturer' },
        year: { value: '2021', source: 'manufacturer' },
        driveModes: { value: 'Sport, Eco, Comfort, Off-road', source: 'manufacturer' },
        torque: { value: '57,6 kgfm', source: 'manufacturer' },
        powerRpm: { value: '5.500 rpm', source: 'manufacturer' },
        torqueRpm: { value: '3.100 rpm', source: 'manufacturer' },
        transmission: { value: 'Automática', source: 'manufacturer' },
        drivetrain: { value: '4x4', source: 'manufacturer' },
        cityConsumption: { value: '6,5 km/l', source: 'technicalDatabase' },
        highwayConsumption: { value: '8,2 km/l', source: 'technicalDatabase' },
        length: { value: '4.811 mm', source: 'manufacturer' },
        width: { value: '1.928 mm', source: 'manufacturer' },
        height: { value: '1.852 mm', source: 'manufacturer' },
        wheelbase: { value: '2.949 mm', source: 'manufacturer' },
        tireType: { value: 'All-terrain', source: 'manufacturer' },
        rim: { value: '17"', source: 'manufacturer' },
        tireWidth: { value: '285 mm', source: 'manufacturer' },
        tireProfile: { value: '70', source: 'manufacturer' },
        tankCapacity: { value: '79 L', source: 'manufacturer' },
        fuelType: { value: 'Gasolina', source: 'manufacturer' },
        loadCapacity: { value: '450 kg', source: 'technicalDatabase' },
        towingCapacity: { value: '1.580 kg', source: 'technicalDatabase' },
    },
    sections: {
        performance: [{ value: 'Tração 4x4', source: 'manufacturer' }, { value: 'Modos de terreno', source: 'manufacturer' }, { value: 'Suspensão preparada para off-road', source: 'manufacturer' }],
        security: [{ value: 'Controle de tração', source: 'manufacturer' }, { value: 'Assistente em descidas', source: 'manufacturer' }, { value: 'Monitoramento de estabilidade', source: 'manufacturer' }],
        technology: [{ value: 'Sistema multimídia', source: 'manufacturer' }, { value: 'Câmeras de apoio', source: 'manufacturer' }, { value: 'Conectividade embarcada', source: 'manufacturer' }],
        comfort: [{ value: 'Interior resistente', source: 'manufacturer' }, { value: 'Boa altura do solo', source: 'technicalDatabase' }, { value: 'Espaço para passageiros', source: 'technicalDatabase' }],
    },
    aiAnalysis: {
        strengths: ['Excelente capacidade off-road', 'Boa altura do solo', 'Visual robusto e aventureiro'],
        weaknesses: ['Consumo elevado', 'Porte grande para uso urbano', 'Conforto inferior ao de SUVs premium'],
        bestUse: 'Off-road, aventura, trilhas e viagens',
        competitors: ['Jeep Wrangler', 'Toyota 4Runner', 'Land Rover Defender'],
    },
};

export const cars = [mustang, bronco];
