import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { COLORS, FEATURE_ADOPTION, FEATURE_META, POWERTRAIN_MIX } from "../../data";
import { ChartTooltip } from "../Shared";
import "./style.css";

export default function Trends({ visibleFeatures, onToggleFeature }) {
  return (
    <section className="insights-trends insights-chart-grid">
      <div className="insights-chart-wide"><div className="insights-panel"><header className="insights-panel-header"><h2>Adoção de recursos ao longo do tempo</h2><p>% de veículos lançados com o recurso de série ou opcional</p></header><div className="insights-panel-body"><div className="insights-legend-toggle">{Object.entries(FEATURE_META).map(([key, meta]) => <button key={key} type="button" className={visibleFeatures[key] ? "" : "off"} onClick={() => onToggleFeature(key)}><i style={{ background: meta.color }} />{meta.label}</button>)}</div><ResponsiveContainer width="100%" height={230}><LineChart data={FEATURE_ADOPTION} margin={{ top: 6, right: 10, left: -18, bottom: 0 }}><CartesianGrid stroke="#e8edf2" vertical={false} /><XAxis dataKey="periodo" tick={{ fill: COLORS.muted, fontSize: 11 }} axisLine={{ stroke: COLORS.border }} tickLine={false} /><YAxis tick={{ fill: COLORS.muted, fontSize: 11 }} axisLine={false} tickLine={false} unit="%" width={40} /><Tooltip content={<ChartTooltip suffix="%" />} />{Object.entries(FEATURE_META).map(([key, meta]) => visibleFeatures[key] && <Line key={key} type="monotone" dataKey={key} name={meta.label} stroke={meta.color} strokeWidth={2} dot={{ r: 2.5, fill: meta.color, strokeWidth: 0 }} />)}</LineChart></ResponsiveContainer></div></div></div>
      <div className="insights-chart-narrow"><div className="insights-panel"><header className="insights-panel-header"><h2>Mix de motorização</h2><p>Por ano de lançamento, todos os segmentos</p></header><div className="insights-panel-body"><ResponsiveContainer width="100%" height={230}><AreaChart data={POWERTRAIN_MIX} margin={{ top: 6, right: 6, left: -18, bottom: 0 }}><CartesianGrid stroke="#e8edf2" vertical={false} /><XAxis dataKey="ano" tick={{ fill: COLORS.muted, fontSize: 11 }} axisLine={{ stroke: COLORS.border }} tickLine={false} /><YAxis tick={{ fill: COLORS.muted, fontSize: 11 }} axisLine={false} tickLine={false} unit="%" width={40} /><Tooltip content={<ChartTooltip suffix="%" />} /><Area type="monotone" dataKey="combustao" stackId="1" name="Combustão" stroke={COLORS.muted} fill={COLORS.muted} fillOpacity={0.45} /><Area type="monotone" dataKey="hibrido" stackId="1" name="Híbrido" stroke={COLORS.cyan} fill={COLORS.cyan} fillOpacity={0.6} /><Area type="monotone" dataKey="plugin" stackId="1" name="Híbrido plug-in" stroke={COLORS.green} fill={COLORS.green} fillOpacity={0.6} /><Area type="monotone" dataKey="eletrico" stackId="1" name="Elétrico" stroke={COLORS.blue} fill={COLORS.blue} fillOpacity={0.7} /></AreaChart></ResponsiveContainer></div></div></div>
    </section>
  );
}
